import type { Product, Role, Industry, Profile, DeliveryMethod, ProductType } from './types';

export const ROLES: Role[] = ['Trader / Portfolio Manager', 'Risk Manager', 'C-Suite / CFO / Treasurer', 'Operations / IT'];

export const INDUSTRIES: Industry[] = [
    'Agriculture and CPG',
    'Banking & Financial Institutions',
    'Coal mining and production',
    'Crude oil, refined products, and NGLs',
    'Environmental credits and certificates',
    'Manufacturing and procurement',
    'Merchant trading',
    'Metals and mining',
    'Natural gas and LNG',
    'Petrochemicals',
    'Transportation and shipping',
    'Utilities, power, and renewables'
];

export const PROFILES: Profile[] = ['Basic (< 10 users)', 'Standard (10-100 users)', 'Advanced (100+ users)'];
export const DELIVERY_METHODS: DeliveryMethod[] = ['On-premise', 'SaaS', 'ION Cloud'];
export const PRODUCT_TYPES: ProductType[] = ['CTRM', 'Complementary'];


export const PRODUCTS: Product[] = [
    {
        productName: 'Agtech',
        description: 'An integrated solution to manage the agricultural product lifecycle from field to fork.',
        role: ['Operations / IT', 'Trader / Portfolio Manager'],
        industries: ['Agriculture and CPG'],
        profile: ['Standard (10-100 users)'],
        deliveryMethod: ['SaaS', 'ION Cloud'],
        productType: 'Complementary',
    },
    {
        productName: 'Algosys',
        description: 'A metallurgical accounting solution for mass balancing and production reconciliation.',
        role: ['Operations / IT'],
        industries: ['Metals and mining'],
        profile: ['Standard (10-100 users)'],
        deliveryMethod: ['SaaS', 'ION Cloud'],
        productType: 'Complementary',
    },
    {
        productName: 'Allegro',
        description: 'A customizable, industry-leading CTRM for utilities and energy companies.',
        role: ['Trader / Portfolio Manager', 'Risk Manager', 'Operations / IT'],
        industries: ['Utilities, power, and renewables', 'Natural gas and LNG', 'Crude oil, refined products, and NGLs'],
        profile: ['Standard (10-100 users)', 'Advanced (100+ users)'],
        deliveryMethod: ['On-premise', 'SaaS', 'ION Cloud'],
        productType: 'CTRM',
    },
    {
        productName: 'Aspect',
        description: 'A multi-tenant, SaaS CTRM for liquid hydrocarbons and metals traders moving off spreadsheets.',
        role: ['Trader / Portfolio Manager'],
        industries: ['Merchant trading', 'Crude oil, refined products, and NGLs', 'Metals and mining'],
        profile: ['Basic (< 10 users)', 'Standard (10-100 users)'],
        deliveryMethod: ['SaaS'],
        productType: 'CTRM',
    },
    {
        productName: 'Carbon Zero',
        description: 'Manage your energy transition with a simple, fast trading and inventory solution that covers the full carbon and renewable certificate lifecycle.',
        role: ['Trader / Portfolio Manager', 'Risk Manager'],
        industries: ['Environmental credits and certificates', 'Utilities, power, and renewables'],
        profile: ['Basic (< 10 users)', 'Standard (10-100 users)'],
        deliveryMethod: ['SaaS', 'ION Cloud'],
        productType: 'Complementary',
    },
    {
        productName: 'Credit Risk',
        description: 'A web-based solution to measure, manage, and mitigate counterparty risk proactively.',
        role: ['Risk Manager', 'C-Suite / CFO / Treasurer'],
        industries: ['Merchant trading', 'Utilities, power, and renewables', 'Banking & Financial Institutions'],
        profile: ['Standard (10-100 users)', 'Advanced (100+ users)'],
        deliveryMethod: ['ION Cloud'],
        productType: 'Complementary',
    },
    {
        productName: 'CxC',
        description: 'A commodity management system for palm oil and other grain and oilseed industries.',
        role: ['Operations / IT'],
        industries: ['Agriculture and CPG'],
        profile: ['Basic (< 10 users)', 'Standard (10-100 users)'],
        deliveryMethod: ['SaaS', 'ION Cloud'],
        productType: 'Complementary',
    },
    {
        productName: 'Decision Support Center (DSC)',
        description: 'Support traders globally by providing access to a market data and news aggregation platform, available on all devices. Mitigate price risk in uncertain and volatile markets with full pricing automation.',
        role: ['Trader / Portfolio Manager'],
        industries: ['Merchant trading', 'Banking & Financial Institutions'],
        profile: ['Standard (10-100 users)'],
        deliveryMethod: ['SaaS', 'ION Cloud'],
        productType: 'Complementary',
    },
    {
        productName: 'FEA',
        description: 'A suite of leading portfolio risk analytics and asset optimization tools for decision support.',
        role: ['Risk Manager', 'Trader / Portfolio Manager'],
        industries: ['Utilities, power, and renewables', 'Merchant trading', 'Banking & Financial Institutions'],
        profile: ['Standard (10-100 users)', 'Advanced (100+ users)'],
        deliveryMethod: ['On-premise', 'SaaS', 'ION Cloud'],
        productType: 'Complementary',
    },
    {
        productName: 'Hedge Accounting',
        description: 'A derivatives analyzer and toolkit to design and assess hedge effectiveness.',
        role: ['C-Suite / CFO / Treasurer', 'Risk Manager'],
        industries: ['Manufacturing and procurement', 'Agriculture and CPG'],
        profile: ['Standard (10-100 users)', 'Advanced (100+ users)'],
        deliveryMethod: ['SaaS', 'ION Cloud'],
        productType: 'Complementary',
    },
    {
        productName: 'Openlink',
        description: 'A comprehensive, multi-commodity CTRM for industry leaders operating at scale.',
        role: ['C-Suite / CFO / Treasurer', 'Trader / Portfolio Manager', 'Risk Manager', 'Operations / IT'],
        industries: ['Banking & Financial Institutions', 'Merchant trading', 'Utilities, power, and renewables', 'Metals and mining'],
        profile: ['Advanced (100+ users)'],
        deliveryMethod: ['On-premise', 'SaaS', 'ION Cloud'],
        productType: 'CTRM',
    },
    {
        productName: 'Precious Metals',
        description: 'A single solution for managing physical bullion inventory across the value chain.',
        role: ['Operations / IT', 'Trader / Portfolio Manager'],
        industries: ['Metals and mining', 'Banking & Financial Institutions'],
        profile: ['Standard (10-100 users)'],
        deliveryMethod: ['SaaS', 'ION Cloud'],
        productType: 'Complementary',
    },
    {
        productName: 'Qmastor',
        description: 'A supply chain management solution to simplify coal and mineral operations and logistics.',
        role: ['Operations / IT'],
        industries: ['Coal mining and production', 'Transportation and shipping', 'Metals and mining'],
        profile: ['Standard (10-100 users)'],
        deliveryMethod: ['On-premise'],
        productType: 'Complementary',
    },
    {
        productName: 'RightAngle',
        description: 'A CTRM with robust scheduling and logistics capabilities for liquid hydrocarbon companies.',
        role: ['Operations / IT', 'Trader / Portfolio Manager', 'Risk Manager'],
        industries: ['Crude oil, refined products, and NGLs', 'Petrochemicals', 'Transportation and shipping'],
        profile: ['Standard (10-100 users)', 'Advanced (100+ users)'],
        deliveryMethod: ['On-premise', 'SaaS', 'ION Cloud'],
        productType: 'CTRM',
    },
    {
        productName: 'Softmar',
        description: 'A shipping solution for vessel chartering and operations integrated with ION’s CTRMs.',
        role: ['Operations / IT'],
        industries: ['Transportation and shipping'],
        profile: ['Standard (10-100 users)'],
        deliveryMethod: ['ION Cloud'],
        productType: 'Complementary',
    },
    {
        productName: 'TriplePoint',
        description: 'An out-of-the-box, multi-commodity CTRM with configurable functionality.',
        role: ['Trader / Portfolio Manager', 'Operations / IT', 'Risk Manager'],
        industries: ['Merchant trading', 'Agriculture and CPG', 'Manufacturing and procurement'],
        profile: ['Standard (10-100 users)'],
        deliveryMethod: ['SaaS', 'ION Cloud'],
        productType: 'CTRM',
    },
    {
        productName: 'WAM',
        description: 'An optimization solution for supply and demand planning, integrated with ION’s CTRMs.',
        role: ['Operations / IT', 'Trader / Portfolio Manager'],
        industries: ['Utilities, power, and renewables', 'Manufacturing and procurement'],
        profile: ['Standard (10-100 users)', 'Advanced (100+ users)'],
        deliveryMethod: ['On-premise', 'SaaS', 'ION Cloud'],
        productType: 'Complementary',
    }
];